config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pet_histories
  resources :pets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'clients#index' #nombre plural controlador y la vista
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :pets, dependent: :destroy
  has_many :pet_histories, :through => :pet
 
  validates :name, presence: true
  

  accepts_nested_attributes_for :pets, allow_destroy: true
 
  def to_s
    name
  end
  
  def pet_client
    pets.count
  end

  
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :client
  has_many :pet_histories, dependent: :destroy
  
  validates :name, presence: true
 

  accepts_nested_attributes_for :pet_histories, allow_destroy: true
  
 def visites
    pet_histories.count
 end
 def to_s
  name
 end
end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
  belongs_to :pet, dependent: :destroy
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @pets = @client.pets
  
    @pet = @pets.find_by(params[:pet_id])
    if @pet != nil
      @weigth_max= @pet.pet_histories.maximum(:weigth)
      @height_max = @pet.pet_histories.maximum(:height)
    end
  end

  
  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email, :client_id,
        pets_attributes: [:id, :name, :breed, :birthdate, :pet_id, :weigth, :height, :_destroy])
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: [:show, :edit, :update, :destroy]

  # GET /pet_histories
  # GET /pet_histories.json
  def index
    @pet_histories = PetHistory.all
    @pet = Pet.select(:id, :pet_id)
    
  end

  # GET /pet_histories/1
  # GET /pet_histories/1.json
  def show

    @pets = Pet.find_by(params[:pet_id])
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
    @pets = Pet.group(:name)
    
  end

  # GET /pet_histories/1/edit
  def edit
    @pets = Pet.all
   
  end

  # POST /pet_histories
  # POST /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully created.' }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1
  # PATCH/PUT /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1
  # DELETE /pet_histories/1.json
  def destroy
    @pet_history.destroy
    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: 'Pet history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:weigth, :height, :diagnosis, :pet_id )
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
   
  end

  # GET /pets/1
  # GET /pets/1.json
  def show

    
    @pet_histories = @pet.pet_histories
   
    #para mostrar datos creamos estas variables
    @weigth_max = @pet_histories.maximum(:weigth)#acá vamos a ocupar la misma variable arriba para no repetir @pet.histories 
    @height_max = @pet_histories.maximum(:height)
    @weigth_avr = @pet_histories.average(:weigth)
    @height_avr = @pet_histories.average(:height)
  end

  # GET /pets/new
  def new
    @pet = Pet.new  
  end

  # GET /pets/1/edit
  def edit
   
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :birthdate, :pet_id,
        pet_histories_attributes: [:weigth, :height, :diagnosis, :client_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_form.html.erb
<div class="row">

  <div class="col-md offset-md-2">
    <div class="form-group">

    <%= form_with(model: client, local: true) do |form| %>
      <% if client.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

          <ul>
            <% client.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name, "Nombre" %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :phone, "Telefono" %>
        <%= form.number_field :phone %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>

      <h3>Mascotas</h3>
      <div class="field" id="pets">
        <%= form.fields_for :pets do |pet_form| %>
        <%= render 'pet_fields', f: pet_form %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Agregar Mascota', form, :pets %>
        </div>
      </div>
      <div class="actions">
        <%= form.submit "Guardar", class:"btn btn-primary" %>
        <%= link_to 'Volver', clients_path, class: "btn btn-light"  %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/clients/_pet_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name, "Nombre"%>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :breed , "Raza"%>
    <%= f.text_field :breed %>
  </div>

  <div class="field">
    <%= f.label :birthdate , "Fecha Nacimiento"%>
    <%= f.date_field :birthdate %>
  </div>


  <%= link_to_remove_association "Remover mascota", f %>
</div>

app/views/clients/edit.html.erb
<h1>Editando Cliente</h1>

<%= render 'form', client: @client %>
<div class="row-3">
  <div class="col-md-8 offset-md-2">
    <%= link_to 'Mostrar', @client %> |
    <%= link_to 'Volver', client_path %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="row-3 container">
  <div class="col-md-8 offset-md-2">
  <p id="notice"><%= notice %></p>
    <h1>Clientes</h1><hr>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Mascotas</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.name %></td>
            <td><%= client.phone %></td>
            <td><%= client.email %></td>
            <td><%= client.pet_client %></td>
            <td><%= link_to 'Mostrar', client %></td>
            <td><%= link_to 'Editar', edit_client_path(client) %></td>
            <td><%= link_to 'Destruir', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <%= link_to 'Nuevo Cliente', new_client_path, class:"btn btn-success" %>
     <%= link_to 'Historial Mascotas', pets_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/clients/new.html.erb
<div class="row-6">
   <div class="col-md-6 offset-md-2">
  <h1>Nuevo Cliente</h1><hr>
  <%= render 'form', client: @client %>
  
  </div>
</div>

app/views/clients/show.html.erb
<div class="row">

  <div class="col-md offset-md-2">
    <p id="notice"><%= notice %></p><hr>
    <p>
      <strong>Cliente:</strong>
      <%= @client.name %>
    </p>
    <p>
      <strong>Telefono:</strong>
      <%= @client.phone %>
    </p>
    <p>
      <strong>Email:</strong>
      <%= @client.email %>
    </p>

      <tbody>
      
        <% @pets.each do |pet| %>
          <tr>
          <td>Nombre:  <%= pet %></td>
          <td>peso máximo:  <%= @weigth_max %></td>
          <td>altura máxima:   <%= @height_max%></td>  
          <%= link_to 'Atenciones', pet, class:"btn btn-link"%> 
          <hr> 
                  
          </tr>
            
        <% end %>
          
      </tbody>
    </table>
    <%= link_to 'Nueva Mascota', new_pet_path(@pet), class: "btn btn-info" %>
    <%= link_to 'Editar', edit_client_path(@client), class: "btn btn-info"%>
    <%= link_to 'Volver', clients_path, class:"btn btn-light" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 
  </head>

  <body>
    <%= yield %>





     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pet_histories/_form.html.erb
<div class="row">

  <div class="col-md offset-md-2">

    <%= form_with(model: pet_history, local: true) do |form| %>
      <% if pet_history.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

          <ul>
            <% pet_history.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :weigth, "Peso" %>
        <%= form.number_field :weigth %>
      </div>

      <div class="field">
        <%= form.label :height, "altura" %>
        <%= form.number_field :height %>
      </div>

      <div class="field">
        <%= form.label :diagnosis, "diagnostico" %>
        <%= form.text_field :diagnosis %>
      </div>
    <div class="field">
        <%= form.label :pet_id %>
      <!--<%= form.text_field :pet_id %>-->
        <%= form.collection_select :pet_id, @pets, :id,  :name %>
      </div>

      <div class="actions">
        <%= form.submit "Guardar", class:"btn btn-success"%>
         <%= link_to 'Volver', pets_path, class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pet_histories/edit.html.erb
<h1>Editando Consulta</h1><hr>

<%= render 'form', pet_history: @pet_history %>
 
<%= link_to 'Mostrar', @pet_history %> |
<%= link_to 'Volver', pet_histories_path %>

app/views/pet_histories/index.html.erb
<div class="row">

  <div class="col-md offset-md-1">

    <p id="notice"><%= notice %></p><hr>

    <h1>Historial Mascota</h1>

    <table>
      <thead>
        <tr>
          <th>Peso</th>
          <th>Altura</th>
          <th>Diagnostico</th>
          <th>Mascota</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pet_histories.each do |pet_history| %>
          <tr>
            <td><%= pet_history.weigth %></td>
            <td><%= pet_history.height %></td>
            <td><%= pet_history.diagnosis %></td>
            <td><%= @pet.name %></td>             
            
            <td><%= link_to 'Mostrar', pet_history %></td>
            <td><%= link_to 'Editar', edit_pet_history_path(pet_history) %></td>
            <td><%= link_to 'Destruir', pet_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
          
      </tbody>

      
    </table>

    <br>

    <%= link_to 'Nueva Atención', new_pet_history_path %>
    <%= link_to 'Volver', pets_path %>
  </div>
</div>

app/views/pet_histories/new.html.erb
<div class="row">

  <div class="col-md offset-md-2">
    <h1>Nueva Atención</h1><hr>

    <%= render 'form', pet_history: @pet_history %>

   
  </div>
</div>

app/views/pet_histories/show.html.erb
<div class="row">

  <div class="col-md offset-md-2">

    <p id="notice"><%= notice %></p>
    <h1>Mascota: <%= @pets.name %></h1>
    <p>
      <strong>Peso:</strong>
      <%= @pet_history.weigth %>
    
    </p>

    <p>
      <strong>Altura:</strong>
      <%= @pet_history.height %>
    </p>

    <p>
      <strong>Diagnostico:</strong>
      <%= @pet_history.diagnosis %>
    </p>

    


    <%= link_to 'Editar', edit_pet_history_path(@pet_history) %> |
    <%= link_to 'Volver', pets_path %>
  </div>
</divs>

app/views/pets/_form.html.erb
<div class="row-2">
  <div class="col offset-md-2">

    <%= form_with(model: pet, local: true) do |form| %>
      <% if pet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

          <ul>
            <% pet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name, "Nombre"%>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :breed, "Raza"%>
        <%= form.text_field :breed %>
      </div>

      <div class="field">
        <%= form.label :birthdate, "Fecha Nacimiento" %>
        <%= form.date_field :birthdate %>
      </div>
      


      <div class="actions">
        <%= form.submit "Guardar", class:"btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<div class="row">

  <div class="col-md offset-md-2">
    <h1>Editando Mascota</h1><hr>

    <%= render 'form', pet: @pet %>

    <%= link_to 'Show', @pet, class:"btn btn-warning" %> |
    <%= link_to 'Back', pets_path , class:"btn btn-light"%>
  </div>
</div>

app/views/pets/index.html.erb
<div class="row">

  <div class="col-md offset-md-2">

    <p id="notice"><%= notice %></p>

    <h1>Mascotas</h1><hr>

    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Raza</th>
          <th>Fecha Nacimiento</th>
          <th>Visitas</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pets.each do |pet| %>
          <tr>
            <td><%= pet.name %></td>
            <td><%= pet.breed %></td>
            <td><%= pet.birthdate %></td>
            <td> <%= pet.visites %> </td>
            <td><%= link_to 'Show', pet %></td>
            <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
            <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>




    <%= link_to 'Nueva Atención', new_pet_history_path, class: "btn btn-success" %>
    <%= link_to 'Volver', clients_path, class:"btn btn-light" %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="row">

  <div class="col-md offset-md-2">
    <h1>Nueva Mascota</h1><hr>

    <%= render 'form', pet: @pet %>

    <%= link_to 'Volver', :back, class: "btn btn-secondary ml-5" %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="row">

  <div class="col-md offset-md-2">
    <p id="notice"><%= notice %></p><hr>


    <p>
      <strong>Nombre:</strong>
      <%= @pet.name %>
    </p>

    <p>
      <strong>Raza:</strong>
      <%= @pet.breed %>
    </p>

    <p>
      <strong>Fecha Nacimiento:</strong>
      <%= @pet.birthdate %>
    </p>


    <table class="table">
      <thead>
        <tr>
          <th>Altura</th>
          <th>Peso</th>
          <th>Fecha de Control</th>
        </tr>
      </thead>

      <tbody>
        <% @pet_histories.each do |pet_history| %>
          <tr>
            <td><%= pet_history.height %></td>
            <td><%= pet_history.weigth %></td>
            <td><%= pet_history.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <table class="table">
      <thead>
        <tr>
          <th>Peso Máximo</th>
          <th>Altura Máxima</th>
          <th>Peso Promedio</th>
          <th>Altura Promedio</th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td><%= @weigth_max %> Kg.</td>
            <td><%= @height_max%> Cms</td>
            <td><%= @weigth_avr%> Kg</td>
            <td><%= @height_avr %> Cms</td>
          </tr>
      </tbody>
    </table>

    <%= link_to 'Volver', :back, class:"btn btn-light"%>
    
  </div>
</div>